=== ProfJerry/UMLanalyser/UMLModelOutpu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	作者：王智立
	创建时间：2015-05-05
	版本：1.0.0
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:uml="http://www.bupt.edu.cn/xml-namespace/UMLModelOutput" targetNamespace="http://www.bupt.edu.cn/xml-namespace/UMLModelOutput" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<!-- XML Schema Definition for generic Managed Object -->
	<xsd:complexType name="UMLModelOutputType">
		<xsd:sequence>
			<xsd:element name="classSet" type="uml:ClassInfoSetType"/>
			<xsd:element name="relationshipSet" type="uml:RelationshipSetType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ClassInfoType">
		<xsd:sequence>
			<xsd:element name="className" type="xsd:string"/>
			<xsd:element name="attributeSet" type="uml:NameTypePairInfoListType"/>
			<xsd:element name="operationSet" type="uml:OperationInfoSetType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ClassInfoSetType">
		<xsd:sequence>
			<xsd:element name="class" type="uml:ClassInfoType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="NameTypePairInfoType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="type" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="NameTypePairInfoListType">
		<xsd:sequence>
			<xsd:element name="item" type="uml:NameTypePairInfoType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<!--
	<xsd:complexType name="AttributeInfoSetType">
		<xsd:sequence>
			<xsd:element name="attribute" type="uml:NameTypePairInfoType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>

	</xsd:complexType>
	-->
	<xsd:complexType name="OperationInfoType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="returnType" type="xsd:string"/>
			<xsd:element name="parameterList" type="uml:NameTypePairInfoListType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="OperationInfoSetType">
		<xsd:sequence>
			<xsd:element name="operation" type="uml:OperationInfoType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="RelationshipSetType">
		<xsd:sequence>
			<xsd:element name="associationList" type="uml:AssociationRelationshipSetType"/>
			<xsd:element name="aggregationList" type="uml:ContainmentRelationshipSetType"/>
			<xsd:element name="compositionList" type="uml:ContainmentRelationshipSetType"/>		
			<xsd:element name="generalizationList" type="uml:GeneralizationRelationshipSetType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ContainmentRelationshipType">
		<xsd:sequence>
			<xsd:element name="containmentRelationshipName" type="xsd:string"/>
			<xsd:element name="superiorClass" type="xsd:string"/>
			<xsd:element name="superiorClassMultiplicity" type="uml:multiplicityType"/>
			<xsd:element name="subordinateClass" type="xsd:string"/>
			<xsd:element name="subordinateClassMultiplicity" type="uml:multiplicityType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ContainmentRelationshipSetType">
		<xsd:sequence>
			<xsd:element name="containmentInfo" type="uml:ContainmentRelationshipType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="multiplicityType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="*"/>
			<xsd:enumeration value="0"/>
			<xsd:enumeration value="0..*"/>
			<xsd:enumeration value="0..1"/>
			<xsd:enumeration value="1"/>
			<xsd:enumeration value="1.."/>
			<xsd:enumeration value="1..*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="AssociationRelationshipType">
		<xsd:sequence>
			<xsd:element name="associationRelationshipName" type="xsd:string"/>
			<xsd:element name="associationDirection" type="uml:DirectionType"/>
			<xsd:element name="fromClass" type="xsd:string"/>
			
			<xsd:element name="fromAssociationAttribute" type="xsd:string"/>
			<xsd:element name="fromMultiplicity" type="uml:multiplicityType"/>
			<xsd:element name="toClass" type="xsd:string"/>
			<xsd:element name="toAssociationAttribute" type="xsd:string"/>
			<xsd:element name="toMultiplicity" type="uml:multiplicityType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="DirectionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="bidirectional"/>
			<xsd:enumeration value="unidirectional"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="AssociationRelationshipSetType">
		<xsd:sequence>
			<xsd:element name="associationInfo" type="uml:AssociationRelationshipType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="GeneralizationRelationshipType">
		<xsd:sequence>
			<xsd:element name="parentClass" type="xsd:string"/>
			<xsd:element name="childClass" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="GeneralizationRelationshipSetType">
		<xsd:sequence>
			<xsd:element name="generalizationInfo" type="uml:GeneralizationRelationshipType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="containmentSetInfo" type="uml:UMLModelOutputType"/>
</xsd:schema>

=== ProfJerry/UMLanalyser/Debug/UMLModelTest-20161107144831.xml
<?xml version="1.0" encoding="UTF-8"?>
<containmentSetInfo xmlns="http://www.bupt.edu.cn/xml-namespace/UMLModelOutput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bupt.edu.cn/xml-namespace/UMLModelOutput
D:\Backup\UMLanalyser\UMLModelOutpu.xsd">
	<classSet>
		<class>
			<className>Class</className>
			<attributeSet>
				<item>
					<name>classID</name>
					<type>integer</type>
				</item>
				<item>
					<name>teacherList</name>
					<type>DNSetType</type>
				</item>
			</attributeSet>
			<operationSet>
			</operationSet>
		</class>
		<class>
			<className>ManagedObject</className>
			<attributeSet>
				<item>
					<name>objectClass</name>
					<type>string</type>
				</item>
				<item>
					<name>objectInstance</name>
					<type>DNType</type>
				</item>
			</attributeSet>
			<operationSet>
			</operationSet>
		</class>
		<class>
			<className>Person</className>
			<attributeSet>
				<item>
					<name>birthday</name>
					<type>string</type>
				</item>
				<item>
					<name>friendList</name>
					<type>DNSetType</type>
				</item>
				<item>
					<name>personID</name>
					<type>integer</type>
				</item>
				<item>
					<name>personName</name>
					<type>string</type>
				</item>
			</attributeSet>
			<operationSet>
				<operation>
					<name>changeName</name>
					<returnType>string</returnType>
					<parameterList>
						<item>
							<name>para2</name>
							<type>string</type>
						</item>
						<item>
							<name>para1</name>
							<type>string</type>
						</item>
					</parameterList>
				</operation>
				<operation>
					<name>getID</name>
					<returnType>int</returnType>
					<parameterList>
						<item>
							<name>para1</name>
							<type>string</type>
						</item>
					</parameterList>
				</operation>
			</operationSet>
		</class>
		<class>
			<className>School</className>
			<attributeSet>
				<item>
					<name>location</name>
					<type>string</type>
				</item>
				<item>
					<name>schoolID</name>
					<type>integer</type>
				</item>
				<item>
					<name>schoolName</name>
					<type>string</type>
				</item>
				<item>
					<name>studentLimit</name>
					<type>integer</type>
				</item>
			</attributeSet>
			<operationSet>
				<operation>
					<name>setStudentLimit</name>
					<returnType>integer</returnType>
					<parameterList>
						<item>
							<name>para2</name>
							<type>integer</type>
						</item>
						<item>
							<name>para1</name>
							<type>integer</type>
						</item>
					</parameterList>
				</operation>
			</operationSet>
		</class>
		<class>
			<className>Student</className>
			<attributeSet>
				<item>
					<name>sex</name>
					<type>string</type>
				</item>
				<item>
					<name>studentNo</name>
					<type>integer</type>
				</item>
			</attributeSet>
			<operationSet>
				<operation>
					<name>changeClass</name>
					<returnType>integer</returnType>
					<parameterList>
						<item>
							<name>para2</name>
							<type>integer</type>
						</item>
						<item>
							<name>para1</name>
							<type>integer</type>
						</item>
					</parameterList>
				</operation>
				<operation>
					<name>changeSchool</name>
					<returnType>integer</returnType>
					<parameterList>
						<item>
							<name>para2</name>
							<type>integer</type>
						</item>
						<item>
							<name>para1</name>
							<type>integer</type>
						</item>
					</parameterList>
				</operation>
			</operationSet>
		</class>
		<class>
			<className>Teacher</className>
			<attributeSet>
				<item>
					<name>classList</name>
					<type>DNSetType</type>
				</item>
				<item>
					<name>phoneNo</name>
					<type>integer</type>
				</item>
				<item>
					<name>position</name>
					<type>string</type>
				</item>
				<item>
					<name>salary</name>
					<type>integer</type>
				</item>
				<item>
					<name>teacherID</name>
					<type>integer</type>
				</item>
			</attributeSet>
			<operationSet>
				<operation>
					<name>changePosition</name>
					<returnType>bool</returnType>
					<parameterList>
						<item>
							<name>para2</name>
							<type>string</type>
						</item>
						<item>
							<name>para1</name>
							<type>integer</type>
						</item>
					</parameterList>
				</operation>
				<operation>
					<name>setSalary</name>
					<returnType>bool</returnType>
					<parameterList>
						<item>
							<name>para2</name>
							<type>integer</type>
						</item>
						<item>
							<name>para1</name>
							<type>integer</type>
						</item>
					</parameterList>
				</operation>
			</operationSet>
		</class>
	</classSet>
	<relationshipSet>
		<associationList>
			<associationInfo>
				<associationRelationshipName>NULL</associationRelationshipName>
				<associationDirection>unidirectional</associationDirection>
				<fromClass>Class</fromClass>
				<fromAssociationAttribute>teacherList</fromAssociationAttribute>
				<fromMultiplicity>1..*</fromMultiplicity>
				<toClass>Teacher</toClass>
				<toAssociationAttribute>classList</toAssociationAttribute>
				<toMultiplicity>0..*</toMultiplicity>
			</associationInfo>
			<associationInfo>
				<associationRelationshipName>NULL</associationRelationshipName>
				<associationDirection>unidirectional</associationDirection>
				<fromClass>Person</fromClass>
				<fromAssociationAttribute>NULL</fromAssociationAttribute>
				<fromMultiplicity>0..*</fromMultiplicity>
				<toClass>Person</toClass>
				<toAssociationAttribute>FriendList</toAssociationAttribute>
				<toMultiplicity>0..*</toMultiplicity>
			</associationInfo>
		</associationList>
		<aggregationList>
			<containmentInfo>
				<containmentRelationshipName>NULL</containmentRelationshipName>
				<superiorClass>Class</superiorClass>
				<superiorClassMultiplicity>1</superiorClassMultiplicity>
				<subordinateClass>Student</subordinateClass>
				<subordinateClassMultiplicity>1..*</subordinateClassMultiplicity>
			</containmentInfo>
			<containmentInfo>
				<containmentRelationshipName>NULL</containmentRelationshipName>
				<superiorClass>School</superiorClass>
				<superiorClassMultiplicity>1</superiorClassMultiplicity>
				<subordinateClass>Teacher</subordinateClass>
				<subordinateClassMultiplicity>1..*</subordinateClassMultiplicity>
			</containmentInfo>
		</aggregationList>
		<compositionList>
			<containmentInfo>
				<containmentRelationshipName>NULL</containmentRelationshipName>
				<superiorClass>School</superiorClass>
				<superiorClassMultiplicity>1</superiorClassMultiplicity>
				<subordinateClass>Class</subordinateClass>
				<subordinateClassMultiplicity>1..*</subordinateClassMultiplicity>
			</containmentInfo>
		</compositionList>
		<generalizationList>
			<generalizationInfo>
				<parentClass>ManagedObject</parentClass>
				<childClass>Class</childClass>
			</generalizationInfo>
			<generalizationInfo>
				<parentClass>ManagedObject</parentClass>
				<childClass>School</childClass>
			</generalizationInfo>
			<generalizationInfo>
				<parentClass>ManagedObject</parentClass>
				<childClass>Person</childClass>
			</generalizationInfo>
			<generalizationInfo>
				<parentClass>Person</parentClass>
				<childClass>Student</childClass>
			</generalizationInfo>
			<generalizationInfo>
				<parentClass>Person</parentClass>
				<childClass>Teacher</childClass>
			</generalizationInfo>
		</generalizationList>
	</relationshipSet>
</containmentSetInfo>
